markdown: redcarpet
baseurl: /nmp
highlighter: true
timezone: Europe/Berlin

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "%{reference}"

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
